stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: Hosted
    steps:
    - task: PublishPipelineArtifact@0
      displayName: Create Artifact
      inputs:
        artifactName: Artifact1
        targetPath: .
